### ISSUE TITLE
Error when I get the pattern from an Object wihtin an array foreach

### ISSUE THREAD

**Issue by kyromoto** [merencia/node-cron#37]
When I try to get the time pattern from an Object within an foreach(Array) I get this error:

node_modules\node-cron\src\convert-expression\month-names-conversion.js:10
      expression = expression.replace(new RegExp(items[i], 'gi'), parseInt(i, 10) + 1);
                             ^

TypeError: Cannot read property 'replace' of undefined
    at convertMonthName (node_modules\node-cron\src\convert-expression\month-names-conversion.js:10:30)
    at interprete (node_modules\node-cron\src\convert-expression\month-names-conversion.js:16:23)
    at interprete (node_modules\node-cron\src\convert-expression\index.js:38:22)
    at validate (node_modules\node-cron\src\pattern-validation.js:45:29)
    at new Task (node_modules\node-cron\src\task.js:27:5)
    at Object.createTask [as schedule] (node-cron\src\node-cron.js:18:16)
    at index.js:59:22
    at Array.forEach (native)
    at index.js:55:18
    at index.js:114:3

**Comment by manojchandrashekar** [comment]
Are you sure you are passing a string for the time pattern? Perform `console.log(typeof timePatternVar)` will help you check.

**Comment by firstCodeOutlaw** [comment]
If anyone finds their way here in 2021, here is what I discovered: the error was thrown by node-cron package due to improper use of cron expressions. You can pass an expression to cron.schedule function like this:
```
const cron = require('node-cron');
cron.schedule('0 0 10 * * *', () => console.log('Will run at 10AM everyday'));
```
Writing a cron expression without the spaces would cause _node_modules\node-cron\src\convert-expression\month-names-conversion.js_ to throw the Cannot read property 'replace' of undefined error. I recommend reading these articles prior to using cron expressions as they distilled the concept for me:
- [4 Ways to Schedule Node Code](https://twilio.com/blog/4-ways-to-schedule-node-code)
- [A Cron Expressions](https://docs.oracle.com/cd/E12058_01/doc/doc.1014/e12030/cron_expressions.htm)

**Comment by nfolkman** [comment]
@firstCodeOutlaw Thank you so much for this response! I couldn't troubleshoot it effectively for the life of me.

**Comment by Snouzy** [comment]
alo, if you are holding the cron time in your `.env`, make sure that he is defined
