### ISSUE TITLE
Run cron every 30 minutes

### ISSUE THREAD

**Issue by k-kentang** [merencia/node-cron#92]
Hi, i have create task with pattern like this (*/30 * * * *)
and its not run every 30 minutes, can you tell me pattern for run every 30 minutes?
Thank you

**Comment by merencia** [comment]
Hi @k-kentang 

this pattern will match every minute that is multiple of 30. As the a hour has minutes from 0 to 59, your pattern will match the unique multiple of 30 in the range 0-59 that is 30, and you job will be performed one time per hour.

I think the patter `0,30 * * * *` will works for you, because this way it will be performed every minute 0 and every minute 30.
